# TensorFlow
### TensorFlow is an open source software library for numerical computation using data flow graphs. 
### Nodes in the graph represent mathematical operations
#### Edges represent the multidimensional data arrays (tensors) passed between them
#### It includes functions for running the state of the art convolutional neural networks and recurrent neural networks for image and text processing

In [2]:
# After installing it we have to run it
import tensorflow as tf
import numpy as np

# Tensors - Tensorflow's main data structure
### A Tensorflow tensor is just a typed, multidimensional array, with additional operations, modeled in the tensor object
## Tensor properties - ranks, shapes and types
### rank - number of tensor dimensions - a rank one tensor is a vector, a rank two tensor a matrix
### Tensor shape - three notational conventions to describe tensor dimensionality, rank, shape and dimension number
<img src='tensors.jpg'/>
## Tensor data types - any of the data types in the table given below can be assigned
<img src='tensors_dt.jpg'/>

# Tensorflow constants and variables and evaluation
### Create constants with tf.constant
### Create variables with tf.Variable
### For the computation to be carried out we need to create a Session and run the tensorflow graph that we have built

In [2]:
hello = tf.constant('hello TF !')
sess = tf.Session()
sess.run(hello)

b'hello TF !'

In [14]:
x = tf.constant(1, name='x')
y = tf.Variable(x + 9, name='y')
print(y)

<tf.Variable 'y_4:0' shape=() dtype=int32_ref>


In [15]:
model = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(y))

10


In [5]:
a = tf.placeholder('int32')
b = tf.placeholder('int32')

y = tf.multiply(a, b)

sess = tf.Session()
sess.run(y, feed_dict={a:2, b:10})

20

# Tensor shape and element access syntax

In [16]:
sess = tf.Session()
tens1 = tf.constant([[[1,2], [2,3]], [[3,4], [5,6]]])
print(sess.run(tens1)[0, 0, 0])
print(sess.run(tens1)[0, 0, 1])
print(sess.run(tens1)[0, 1, 0])
print(sess.run(tens1)[0, 1, 1])
print(sess.run(tens1)[1, 1, 0])
print(tens1.shape)
tens1

1
2
2
3
5
(2, 2, 2)


<tf.Tensor 'Const_3:0' shape=(2, 2, 2) dtype=int32>

# Inter conversion between numpy and tensors

In [17]:
sess = tf.Session() #start a new Session Object
x_data = np.array([[1.,2.,3.],[3.,2.,6.]]) # 2x3 matrix
x = tf.convert_to_tensor(x_data, dtype=tf.float32)
print (x)

Tensor("Const_4:0", shape=(2, 3), dtype=float32)


## Saving dataflow graphs using protocol buffers

In [38]:
g = tf.Graph()
with g.as_default():
    sess = tf.Session()
    W_m = tf.Variable(tf.zeros([10, 5]))
    x_v = tf.placeholder(tf.float32, [None, 10])
    result = tf.matmul(x_v, W_m)
    print (g.as_graph_def())

node {
  name: "zeros"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 10
          }
          dim {
            size: 5
          }
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "Variable"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 10
        }
        dim {
          size: 5
        }
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "Variable/Assign"
  op: "Assign"
  input: "Variable"
  input: "zeros"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }


# Basic tensor methods

In [5]:
# We could create an interactive session and use it across
# isess = tf.InteractiveSession()
sess = tf.Session()
x = tf.constant([[2, 5, 3, -5], [0, 3,-2, 5], [4, 3, 5, 3], [6, 1, 4, 0]])
y = tf.constant([[4, -7, 4, -3, 4], [6, 4,-7, 4, 7], [2, 3, 2, 1, 4], [1, 5,
5, 5, 2]])
floatx = tf.constant([[2., 5., 3., -5.], [0., 3.,-2., 5.], [4., 3., 5.,
3.], [6., 1., 4., 0.]])
# if we have an interactive session going on then we can run eval to get results
# tf.transpose(x).eval() # Transpose matrix
sess.run(tf.transpose(x))
# we have to explicitly close interactive session to release resources
# isess.close()

array([[ 2,  0,  4,  6],
       [ 5,  3,  3,  1],
       [ 3, -2,  5,  4],
       [-5,  5,  3,  0]])

In [6]:
sess = tf.Session()
sess.run(tf.matrix_inverse(floatx))

array([[-0.00855745,  0.10513447, -0.18948655,  0.29584354],
       [ 0.12958434,  0.12224938,  0.01222495, -0.05134475],
       [-0.01955992, -0.18826404,  0.28117359, -0.18092909],
       [-0.08557458,  0.05134474,  0.10513448, -0.0415648 ]], dtype=float32)

## Reduction
### An operation that  applies an operation across one of the tensor's dimensions  leaving it with one less dimension

In [7]:
sess = tf.Session()
x = tf.constant([[1, 2, 3], [3, 2, 1], [-1,-2,-3]])
print(x.shape)
boolean_tensor = tf.constant([[True, False, True],[False, False,
True],[True, False, False]])
# change reduction_indices to 0 and check to get a complete grasp over it
print(sess.run(tf.reduce_prod(x, reduction_indices=1)))
print(sess.run(tf.reduce_min(x, reduction_indices=1)))
print(sess.run(tf.reduce_max(x, reduction_indices=1)))

(3, 3)
[ 6  6 -6]
[ 1  1 -3]
[ 3  3 -1]


# Tensor Segmentation
### Tensor segmentation is a process in which one of the dimensions is reduced, and the resulting elements are determined by an index row
### If some elements in the row are repeated, the corresponding index goes to the value in it, and the operation is applied between the indexes with repeated indexes.

In [21]:
sess = tf.Session()
seq_ids = tf.constant([0, 1, 1, 2, 2,])
tens1 = tf.constant([[2, 5, 3, -5], [0, 3, 2, -5],
                    [4, 3, 5, 3], [6, 1, 4, 0],
                    [6, 1, 4, 0]])
print('shape of tens1 ', tens1.shape)
print(sess.run(tf.segment_sum(tens1, seq_ids)))

shape of tens1  (5, 4)
[[ 2  5  3 -5]
 [ 4  6  7 -2]
 [12  2  8  0]]


In [8]:
sess = tf.Session()
tsqids = tf.constant([0, 1, 1, 1, 1])
tens_test = tf.constant([[3, 2, 4], [2, 3, 4], [4, 2, 3], [5, 7, 8], [1, 1, 1]])
print(tens_test.shape)
# the index row must have the same number of elements as dimension 0 of the input
# the sgement operation will start from the index and carry on till it increments
print('so here 0, 0 will add first two and 1, 1, 1 will add next three and we will get 2 x 3')
print(sess.run(tf.segment_sum(tens_test, tf.constant([0, 0, 1, 1, 1]))))
print('here it will start from 0 and add from 1 onward for the second row of the output')
print(sess.run(tf.segment_sum(tens_test, tf.constant([0, 1, 1, 1, 1]))))
print('here we start from 0, accumulate row 0, for pos 1 we have index row specifying 2 so we get a zero'
     '\nand then we go to position 2 and from backwards accumulate rows 1, 2, 3, 4')
print(sess.run(tf.segment_sum(tens_test, tf.constant([0, 2, 2, 2, 2]))))
print('here we are starting from 2 and we go to 2 and backward accumulate everything while generating 0 for first two rows')
print(sess.run(tf.segment_sum(tens_test, tf.constant([2, 2, 2, 2, 2]))))



(5, 3)
so here 0, 0 will add first two and 1, 1, 1 will add next three and we will get 2 x 3
[[ 5  5  8]
 [10 10 12]]
here it will start from 0 and add from 1 onward for the second row of the output
[[ 3  2  4]
 [12 13 16]]
here we start from 0, accumulate row 0, for pos 1 we have index row specifying 2 so we get a zero
and then we go to position 2 and from backwards accumulate rows 1, 2, 3, 4
[[ 3  2  4]
 [ 0  0  0]
 [12 13 16]]
here we are starting from 2 and we go to 2 and backward accumulate everything while generating 0 for first two rows
[[ 0  0  0]
 [ 0  0  0]
 [15 15 20]]


# Sequences

In [9]:
# Sequences
sess = tf.Session()
x = tf.constant([[2, 5, 3, -5], [0, 3,-2, 5], [4, 3, 5, 3], [6, 1, 4, 0]])
print('shape of x ', x.shape)
listx = tf.constant([1,1,1,2,3,4,5,6,7,8])
listy = tf.constant([4,5,8,9])
print('minimum along dimension 0 indices: ', sess.run(tf.argmin(x, 0)))
print('minimum along dimension 1 indices: ', sess.run(tf.argmin(x, 1)))
# unique finds distinct elements in a 1 d vector
print(sess.run(tf.unique(listx)[0]))
print(sess.run(tf.setdiff1d(listx, listy)[0]))


shape of x  (4, 4)
minimum along dimension 0 indices:  [1 3 1 0]
minimum along dimension 1 indices:  [3 2 1 3]
[1 2 3 4 5 6 7 8]
[1 1 1 2 3 6 7]


# Tensor Shape Transformations

In [10]:
sess = tf.Session()
x = tf.constant([[2, 5, 3, -5], [0, 3,-2, 5], [4, 3, 5, 3], [6, 1, 4, 0]])
print('shape of x ', sess.run(tf.shape(x)))
print('size of x ', sess.run(tf.size(x)))
print('rank of x ', sess.run(tf.rank(x)))
print('reshaping x ', sess.run(tf.reshape(x, [2, 8])))
tsqdem = tf.constant([[2], [3], [4]])
print('tsqdem tensor for squeezeing demo shape: ', tsqdem.shape)
print('tsqdem\n', sess.run(tsqdem), '\ntsqdem squeezed ', sess.run(tf.squeeze(tsqdem)))
print('Expanidng dimension across dim 0\n', sess.run(tf.expand_dims(x, 0)), '\nThe resulting shape\n', tf.expand_dims(x, 0).shape)

shape of x  [4 4]
size of x  16
rank of x  2
reshaping x  [[ 2  5  3 -5  0  3 -2  5]
 [ 4  3  5  3  6  1  4  0]]
tsqdem tensor for squeezeing demo shape:  (3, 1)
tsqdem
 [[2]
 [3]
 [4]] 
tsqdem squeezed  [2 3 4]
Expanidng dimension across dim 0
 [[[ 2  5  3 -5]
  [ 0  3 -2  5]
  [ 4  3  5  3]
  [ 6  1  4  0]]] 
The resulting shape
 (1, 4, 4)


In [11]:
# Slicing
sess = tf.Session()
print(sess.run(tf.slice(x, [1, 1], [3, 3])))

[[ 3 -2  5]
 [ 3  5  3]
 [ 1  4  0]]


In [12]:
# Splitting
sess = tf.Session()
x1, x2 = sess.run(tf.split(axis=0, num_or_size_splits=2, value=x))
print(x1)
print(x2)

[[ 2  5  3 -5]
 [ 0  3 -2  5]]
[[4 3 5 3]
 [6 1 4 0]]


In [13]:
#Tiling - repeat n numbre of times
sess = tf.Session()
# the second argument to the method is a one d array with length equal to number of dimensions of the input
print(sess.run(tf.tile(x1, [1, 1])))
print(sess.run(tf.tile(x1, [1, 2])))

[[ 2  5  3 -5]
 [ 0  3 -2  5]]
[[ 2  5  3 -5  2  5  3 -5]
 [ 0  3 -2  5  0  3 -2  5]]


In [14]:
?tf.tile
# ?tf.pad

In [17]:
# Padding
sess = tf.Session()
t = tf.constant([[1, 2, 3], [4, 5, 6]])
print(t.shape)
print('rank of t ', sess.run(tf.rank(t)))
# Thus paddings has to be of shape [2, 2]
# [1, 1] below indicates values to add  1 value before and 1 value after the contents of the tensor in the first dimension
# [2, 2] below indicates 2 values to add before and 2 values after the contents of the tensor in the second direction
paddings = tf.constant([[1, 1,], [2, 2]])
# so in this case we will have a shape of 4 x 7 - 1 + 2 + 1, 2 + 3 + 2
# There are 3 modes - Constant, Reflect, Symmetric - Constant will add 0s, Reflect and Symmetric - the data
print('\nConstant padding\n', sess.run(tf.pad(t, paddings, 'CONSTANT')))
print('\nReflect padding\n', sess.run(tf.pad(t, paddings, 'REFLECT')))
print('\nSymmetric padding\n', sess.run(tf.pad(t, paddings, 'SYMMETRIC')))

(2, 3)
rank of t  2

Constant padding
 [[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]]

Reflect padding
 [[6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]]

Symmetric padding
 [[2 1 1 2 3 3 2]
 [2 1 1 2 3 3 2]
 [5 4 4 5 6 6 5]
 [5 4 4 5 6 6 5]]


In [24]:
sess = tf.Session()
t_matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
t_array = tf.constant([1,2,3,4,9,8,6,5])
t_array2= tf.constant([2,3,4,5,6,7,8,9])
print('\nConcatenating two arrays\n', sess.run(tf.concat(axis=0, values=[t_array, t_array2])))
print('\nStacking two arrays\n', sess.run(tf.stack(axis=1, values=[t_array, t_array2])))
print('\nUnstacking a matrix\n ', sess.run(tf.unstack(t_matrix)))
# For reverse, we have to provide the matrix and the list of diension numbers along which
# we have to carry out the reverse operation
# check out with 0 alone, 1 alone and then both and should be clear
print('\nReversing a matrix\n ', sess.run(tf.reverse(t_matrix, [0, 1])))


Concatenating two arrays
 [1 2 3 4 9 8 6 5 2 3 4 5 6 7 8 9]

Stacking two arrays
 [[1 2]
 [2 3]
 [3 4]
 [4 5]
 [9 6]
 [8 7]
 [6 8]
 [5 9]]

Unstacking a matrix
  [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

Reversing a matrix
  [[9 8 7]
 [6 5 4]
 [3 2 1]]


# Reading Files
# CSV Files

In [25]:

filename_queue = tf.train.string_input_producer(["iris.csv"])
reader = tf.TextLineReader(skip_header_lines=1)
key, value = reader.read(filename_queue)
record_defaults = [ [0.], [0.], [0.], [0.], [0.]]
col1, col2, col3, col4, col5 = tf.decode_csv(value, record_defaults=record_defaults)
features = tf.stack([col2, col3, col4, col5])

with tf.Session() as sess:
    
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord, sess=sess)
    
    for iteration in range(150):
        try:
            example, label = sess.run([features, col1])
            print(label, example)
        except Exception as exc:
            print(exc)
        
    coord.request_stop()
    coord.join(threads)

0.0 [ 5.0999999   3.5         1.39999998  0.2       ]
1.0 [ 4.9000001   3.          1.39999998  0.2       ]
2.0 [ 4.69999981  3.20000005  1.29999995  0.2       ]
3.0 [ 4.5999999  3.0999999  1.5        0.2      ]
4.0 [ 5.          3.5999999   1.39999998  0.2       ]
5.0 [ 5.4000001   3.9000001   1.70000005  0.40000001]
6.0 [ 4.5999999   3.4000001   1.39999998  0.30000001]
7.0 [ 5.         3.4000001  1.5        0.2      ]
8.0 [ 4.4000001   2.9000001   1.39999998  0.2       ]
9.0 [ 4.9000001  3.0999999  1.5        0.1      ]
10.0 [ 5.4000001   3.70000005  1.5         0.2       ]
11.0 [ 4.80000019  3.4000001   1.60000002  0.2       ]
12.0 [ 4.80000019  3.          1.39999998  0.1       ]
13.0 [ 4.30000019  3.          1.10000002  0.1       ]
14.0 [ 5.80000019  4.          1.20000005  0.2       ]
15.0 [ 5.69999981  4.4000001   1.5         0.40000001]
16.0 [ 5.4000001   3.9000001   1.29999995  0.40000001]
17.0 [ 5.0999999   3.5         1.39999998  0.30000001]
18.0 [ 5.69999981  3.79999995  1

# Reading image files

In [68]:
filename_queue =tf.train.string_input_producer(["./bengal_cat.jpg"])
reader = tf.WholeFileReader()
key, value = reader.read(filename_queue)
image=tf.image.decode_jpeg(value)
flipImageUpDown=tf.image.encode_jpeg(tf.image.flip_up_down(image))
flipImageLeftRight=tf.image.encode_jpeg(tf.image.flip_left_right(image))
with tf.Session() as sess:
# tf.initialize_all_variables().run(session=sess)
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord, sess=sess)
    example = sess.run(flipImageLeftRight)
    print(example)
    file=open ("flippedUpDown.jpg", "wb+")
    file.write (flipImageUpDown.eval(session=sess))
    file.close()
    file=open ("flippedLeftRight.jpg", "wb+")
    file.write (flipImageLeftRight.eval(session=sess))
    file.close()
    
    coord.request_stop()
    coord.join(threads)

b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x01,\x01,\x00\x00\xff\xdb\x00C\x00\x02\x01\x01\x01\x01\x01\x02\x01\x01\x01\x02\x02\x02\x02\x02\x04\x03\x02\x02\x02\x02\x05\x04\x04\x03\x04\x06\x05\x06\x06\x06\x05\x06\x06\x06\x07\t\x08\x06\x07\t\x07\x06\x06\x08\x0b\x08\t\n\n\n\n\n\x06\x08\x0b\x0c\x0b\n\x0c\t\n\n\n\xff\xdb\x00C\x01\x02\x02\x02\x02\x02\x02\x05\x03\x03\x05\n\x07\x06\x07\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\xff\xc0\x00\x11\x08\x00\xb2\x01\x1b\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1f\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x10\x00\x02\x01\x03\x03\x02\x04\x03\x05\x05\x04\x04\x00\x00\x01}\x01\x02\x03\x00\x04\x11\x05\x12!1A\x06\x13Qa\x07"q\x142\x81\x91\xa1\x08#B\xb1\xc1\x15R\xd1\xf0$3br\x82\t\n\x16\x17\x18\x19\x1a%&\'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz\x83\x84\x85\x86\x87\x88\x89\x8a\x92\x93\x94\x95\x96\x97\x98\x9

In [69]:
ls f*.jpg

 Volume in drive C is Windows
 Volume Serial Number is 30AC-FF22

 Directory of C:\Users\Samar\OneDrive\pythonml\pythonml

05/22/2018  14:33            13,984 flippedLeftRight.jpg
05/22/2018  14:33            13,836 flippedUpDown.jpg
               2 File(s)         27,820 bytes
               0 Dir(s)  25,473,654,784 bytes free
